### ISSUE TITLE
コンペに競技を登録するUIを追加する

### ISSUE THREAD

**Issue by euphoria108** [opthub-org/opthub#3]
コンペ編集ページに競技を追加するUIをつける
フォームのイメージはこんな感じ
![](https://camo.qiitausercontent.com/8e60ed3de25985e86908fefd478bf754d151ac94/68747470733a2f2f71696974612d696d6167652d73746f72652e73332e61702d6e6f727468656173742d312e616d617a6f6e6177732e636f6d2f302f313133303434322f66343333376638362d353065662d346438312d336334392d3932623033343235376664652e676966)

↑のようなUIのソースコード：https://hand28.hatenadiary.jp/entry/2018/12/21/181550

競技の登録に必要な情報
```yaml
matches:
- name: str  # len>1
  budget: int  # val>0
  problem: str  # len>1
  indicator: str  # len>1
  environments:
  - public: bool  # default=True
    key: str  # len>1
    value: jsonb  # val=any
```
